# API preparation

Export small lookup tables that the strategy API needs into `src/data/`.
`data/` is not committed to git, so the API cannot read from there.

In [1]:
import pandas as pd
from pathlib import Path

src_path = Path("../data/processed/pit_loss.parquet")
pit_loss = pd.read_parquet(src_path)

print(pit_loss.shape)
pit_loss.head()

(24, 3)

                      Event  PitLoss  Stops
0         Monaco Grand Prix   19.084     41
1       Canadian Grand Prix   19.747     45
2  Saudi Arabian Grand Prix   20.203     21
3        Belgian Grand Prix   20.262     45
4     Australian Grand Prix   20.462     30

In [2]:
assert pit_loss["Event"].is_unique
assert pit_loss[["Event", "PitLoss"]].notna().all().all()
assert pit_loss["PitLoss"].between(10, 45).all()

print("OK:", len(pit_loss), "events")

OK: 24 events

In [3]:
out_dir = Path("../src/data")
out_dir.mkdir(exist_ok=True)

out_path = out_dir / "pit_loss.csv"
pit_loss.round(2).to_csv(out_path, index=False)

print("saved:", out_path.resolve())

saved: C:\Users\vova1\Documents\vscodefiles\resume projects\f1 project\src\data\pit_loss.csv

In [4]:
check = pd.read_csv(out_path)

print(check.shape)
print(check.dtypes)
check.head()

(24, 3)
Event       object
PitLoss    float64
Stops        int64
dtype: object

                      Event  PitLoss  Stops
0         Monaco Grand Prix    19.08     41
1       Canadian Grand Prix    19.75     45
2  Saudi Arabian Grand Prix    20.20     21
3        Belgian Grand Prix    20.26     45
4     Australian Grand Prix    20.46     30